### ISSUE TITLE
Finish Task 6/7

### ISSUE THREAD

**Issue by DLND8** [stefanhaering/pattern_and_trends#1]
Please create a simple ggplot or tmap with your posmo data

**Comment by stefanhaering** [comment]
I have added the plot and comitted the file again.

**Comment by DLND8** [comment]
You also need to push it

**Comment by stefanhaering** [comment]
Oh, yes. I have had an error yesterday and have not seen it. I had to pull first before I was able to push... Now you should see it.

**Comment by DLND8** [comment]
Thanks you can consider Exercise 2 done 👍
